### ISSUE TITLE
Dosn't support Windows 7

### ISSUE THREAD

**Issue by sponnusa** [agourlay/ruxguitar#3]
The error is:

ruxguitar.exe - Entry Point Not Found. The procedure entry point ProcessPrng could not be located in the dynamic link library bcryptprimitives.dll. 

Solution is to downgrade rust to 1.75

**Comment by agourlay** [comment]
I have published the Windows binaries as a best effort given I do not own a Windows machine to test.

Is there a know issue regarding Rust 1.75+ on Windows 7?

**Comment by VladasZ** [comment]
Yeah `rust` is dropping Windows 7 and 8 support: https://github.com/rust-lang/compiler-team/issues/651
They are [Tier 3](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-3) targets now.

I tried to run `ruxguitar` on Windows 7 and I got the same error.

**Comment by VladasZ** [comment]
Sounds reasonable until one of the core crates of the project will require rust version `1.75+`. After that `Windows 7` support can be dropped. Considering that even Microsoft stopped its mainstream support almost 10 years ago.

**Comment by VladasZ** [comment]
Another idea is to build `Tier 3` target with nightly compiler. Currently I'm experimenting with apple TV which is Tier 3 too and I build libraries for it with this command:

**Comment by agourlay** [comment]
Thanks for the input :+1: 

I went with the hardcoded toolchain on 1.75 on CI.

This issue is now fixed in [0.1.2](https://github.com/agourlay/ruxguitar/releases/tag/v0.1.2)
