### ISSUE TITLE
Failed to read GP file: dialog window closed without selecting a file

### ISSUE THREAD

**Issue by Eidonko** [agourlay/ruxguitar#4]
Hello, I have downloaded your Linux binary on my Thinkpad T520
(T520 5.15.0-116-generic #126-Ubuntu SMP Mon Jul 1 10:14:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux)

When I launch the program and I click on Open File I get the following message:

$ ./ruxguitar  
[2024-07-20T11:59:11Z WARN  ruxguitar::ui::application] Failed to read GP file: dialog window closed without selecting a file

Could you please help me? Thank you very much

Kind regards,
Eidon

**Comment by agourlay** [comment]
Which desktop environment are you using?

**Comment by Eidonko** [comment]
> Which desktop environment are you using?

XFCE4

**Comment by agourlay** [comment]
I am also using xfce4 (Xfce 4.18) so it can't be it.

It must be some kind of dependency issue according to https://docs.rs/rfd/latest/rfd/#xdg-desktop-portal-backend

**Comment by agourlay** [comment]
Is possible for you to try installing the `XDG Destop Portal`? 

`sudo apt-get install -y xdg-desktop-portal`

**Comment by agourlay** [comment]
A user with a similar issue reported that install that package fixed the problem.

**Comment by agourlay** [comment]
Sorry I am slowly running out of ideas here :thinking: 

I am using `1.18.4-` for this package, which version did you install?

**Comment by ms1331** [comment]
> A user with a similar issue reported that installing that package fixed the problem.

I actually installed the xdg-desktop-portal-gtk package as well, not only xdg-desktop-portal based on the table here https://wiki.archlinux.org/title/XDG_Desktop_Portal#List_of_backends_and_interfaces

**Comment by Eidonko** [comment]
Sorry...
v. 1.1.3
That's the version I got from apt-get install

-- 
 Sent with Tuta; enjoy secure & ad-free emails: 
 https://tuta.com


Jul 24, 2024, 15:37 by ***@***.***:

**Comment by Eidonko** [comment]
Oh, nice! I installed it and now the file dialog opens up! Thank you!



Jul 24, 2024, 15:55 by ***@***.***:

**Comment by agourlay** [comment]
Great to hear, have fun with ruxguitar!

@ms1331 Thank you very much for chiming in :pray: 

I have updated the FAQ with clearer instruction regarding the XDG desktop portal
https://github.com/agourlay/ruxguitar/commit/032ce43be5d13d933909c19f588b151d3dc64961
